# Config file for automatic testing at travis-ci.org

language: python

# Faster, containerized builds
sudo: false
cache: pip
python:
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"

env:
  # Lowest supported IPython version
  - SHELLS="ipython==4.2.0"
  # Latest IPython
  - SHELLS="ipython"
  - SHELLS="ptpython==0.34"

matrix:
  # IPython>=6.0 is not supported on py2
  exclude:
    - python: "2.7"
      env: SHELLS="ipython"
    - python: "pypy"
      env: SHELLS="ipython"
  include:
    - python: "2.7"
      env: SHELLS="ipython>=5.0,<6.0"
    - python: "pypy"
      env: SHELLS="ipython>=5.0,<6.0"


install:
  - pip install -U .
  - pip install -r dev-requirements.txt
  - pip install -U "$SHELLS"

script: inv test
